### ISSUE TITLE
Design for case filters

### ISSUE THREAD

**Issue by dracos** [mysociety/noiseworks#22]
Prototype has them slide in from side on mobile
![image](https://user-images.githubusercontent.com/154364/124781897-afc63880-df3b-11eb-8981-a6352ddffb85.png)

User stories: 4C (to work well on mobile)

**Comment by LouiseMySociety** [comment]
CSS & Javascript are needed for this.

**Comment by lizettal** [comment]
Link to design trello board: https://trello.com/c/hOgGVnoU/950-noiseworks-design-for-case-filters

**Comment by dracos** [comment]
Superseded by that ticket.
