### ISSUE TITLE
Front end for case actions

### ISSUE THREAD

**Issue by dracos** [mysociety/noiseworks#23]
Prototype has reassign/log action slide up from bottom - but would separate page be as good. Have started with that anyway.

User stories: 4C (to work well on mobile)

**Comment by mySocietyClive** [comment]
Moving this conversation here from Slack, so there's a record of it.

_Clive Gordon - So was looking at ticket which talks about using a modal/pop up type component... I'm thinking as @matthew has suggested perhaps it's better to just use a separate page to log an action... from what I've read modals are better used as a last resort and for things that need more urgent attention like when a user session is about to time out:
https://paper.dropbox.com/doc/Modal-dialog-boxes-jbsTPoITg37IIc6ybjetM

Clive Gordon Example how home office use modal: https://design.homeoffice.gov.uk/patterns/stop-a-service-timing-out

Matthew Somerville - makes sense to me, yeah, so if you wanted to check the separate page I made for any styling improvements, that'd be good ta_
