### ISSUE TITLE
Models for complaints and cases

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#3]
A case includes all the information about a particular noise nuissance that is happening at a particular location.

A case may include one or more complaints (by the same or different people), as well as a history of actions taken towards resolving the nosie nuissance.

A case has a reference number, which is quoted to the citizen, and is also used internally when discussing the case.

Throughout its lifetime, a case might be assigned to different officers. And different actions might need to happen (either automatically or manually) when it’s been a certain amount of time since the case was last updated.

Sometimes it becomes clear that two previously separate ongoing cases are actually about the same noise nuissance at the same location. If this happens, we want to be able to "merge" the cases, so that officers can handle all information in one place. Ideally the old case reference numbers should continue to work.

Need to pin down what metadata is stored at the "Complaint" level, and what’s at the "Case" level. I’m wondering whether actually a case might be a combination of 1 "nuissance" (a specific category of thing, at a specific location, at a specific time or repeating pattern of times), 1 or more "complaints", and 1 or more updates/notes/etc.

Could do with chewing this over with a developer, to work out the right questions to ask to get to the bottom of the best structure.

**Comment by dracos** [comment]
## Cases and complaints

Here are the fields the noise reporting form asks for at present:
* Existing? (Pick existing report)
* Reporter details - name, email, phone
* Best time (weekdays/weekends/evenings)
* Best method (email/phone)
* Reporter's postcode => Address
* Kind of noise (list of things)
* Where (commercial or residential)
* Estates? (Y/N/DK)
* Source location => Address or map click with radius
* Happening now Y/N
*Happening pattern Y/N
* If yes - happening days and happening times (morning/daytime/evening/night)
* If no - when does it happen (free text)
* Any more details

Of those fields, I would say a Case is:
* Kind of noise (list of things)
* Source location => Address or map click with radius
* Where (commercial or residential)
* Estates? (Y/N/DK) - this could be auto worked out if the source is an Address?

And a Complaint is:
* Reporter name, email, phone, postcode, address
* Happening now Y/N
* Happening pattern Y/N (yes, days/times, no, when free text)
* Any more details

That leaves the per-reporter but not really per-complaint settings:
* Best time (weekdays/weekends/evenings)
* Best method (email/phone)

These could be data on the 'user', that could be updated whenever they make a new Complaint.

Other things a Case needs:
* Reference
* State?
* Assigned officer(s)

Does a Complaint need anything else? Should it store personal details per Complaint or have a User? User would presumably be name/email/phone/address/postcode - but I guess people can move... So address/postcode on Complaint at its time? Same for email/phone, or let people update them?

## Updates

Probably need more information here, but at a bare minimum a free text field for whatever the action was. Not sure if needs categorising or what.

**Comment by zarino** [comment]
I’ve been meaning to share this diagram with you all week, from today’s Hackney Show & Tell:

![Screenshot 2021-05-26 at 18 21 32](https://user-images.githubusercontent.com/739624/119704265-586a7e00-be4f-11eb-8e3e-960afd7da15f.png)

My (imperfect) attempt at visualising the different "things" that people have been talking about in the Discovery and Alpha so far. Lots of parallels with what you’ve outlined above. A few comments I’ll leave here, before we discuss in person:

* Not sure it needs to be modelled separately from a case, but it feels like there’s value to a conceptual distinction between the "underlying issue" of a case (which as you say, is a type of noise, at a particular location – usually a property but sometimes technically a vehicle) versus other meta information about the case (like reference number, current assignee).
   * When officers talk about "combining cases", this "underlying issue" is what they’re doing their mental `JOIN` on – ie: "are these two cases about the same underlying issue? If so, they’re duplicates."
* "Actions" have come out of the alpha testing as a fairly natural way of recording progress in a case. Officers check the actions that have taken place on a case, to work out what should happen next, as well as to prioritise which cases to deal with first. I have a big long (non-exhaustive) list of what these "actions" might be – not clear to me how "structured" we need to make them, but they definitely all feel like a common type of "object", which is associated with a case.
   * I’m not sure how "state" fits in with cases. Maybe it’s just "open" or "closed". Or maybe it really shouldn’t exist at all, and all filtering/prioritising should be done based on which actions have been logged on each case. eg: "Hide all cases where there hasn’t been a new action for the last 4 weeks", or "Show me cases where there has been an action of ‘abatement notice issued’ followed by another complaint".
* I simplified the diagram above for the presentation, but my other sketches had other related models, external to the "case" – like "person" and "property".
   * Same as you, I figure contact preferences are an example of a thing stored at the "person" level, not the "complaint" level.
   * Interesting question around whether we combine the concepts of "person" and "user", or whether it’s useful to keep them separate. For example, we likely want to record the "perpetrator(s)" of the noise in a case, and it’d be useful to be able to see all cases a particular perpetrator has been involved in. Does that mean we want a related "perpetrator" model, or are "users" ("reporters"/"complainants") and "perpetrators" really all just the same "person" model?

**Comment by dracos** [comment]
Perhaps, to be generic, ActionCategory should be a model, so they can add their own types of action to be used when creating a new action.

Yeah, the 'state' does seem odd and confrontational - 'closing' something that is still happening.

Property model can sit externally in council API, I think, unless we need to store our own data about them.

On users/people, someone could be a perpetrator and a complainer, is that something that's wanted to be known? I guess if two people next door are complaining about each other all the time, that might then show up from that. You'd have a many-to-many Perpetrator table joining users and cases, and every complaint would link to a user as the Complainant.
