### ISSUE TITLE
Model for citizen users

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#4]
Aside from the obvious, there will need to be some relationship between users and their complaints (or cases?)

I’m currently working out whether a user phone number and/or email address are required by the noise team. I think they _really_ want the phone number – not clear whether they’d be able to handle a complaint without an associated email address.

Need to consider how residents will "log in" to view their past complaints/cases, and update ongoing complaints/cases. Can we do something magic that doesn’t require them to pick and remember a password? (emailing a magic link, or SMS-ing a verification code?)

**Comment by dracos** [comment]
We can do that, yes. Just to note one reason I picked Starling over Monzo for current account recently was that the only way to log in on Monzo was to send a "magic link" email and I don't have email on my phone, so couldn't do that.

We can send email or text message - issue could arise if they have made reports via both methods.

**Comment by dracos** [comment]
Okay, done a lot of research and looking into this. Nothing I have found existing appears to do what I like, but shouldn't be too tricky to piece together some things.

Requirements
* Submission form accepts email or phone or both (might have confirmation, might not)
* You can 'log in' with email or phone in some manner and see all 'your' cases/complaints
* Staff can log in via Google OAuth or normal username/password

Existing packages:
* django-phonenumber-field looks like a good package for storing the phone number, regardless (some of below use it);
* django-email-phone-user - an abstract base user with username automatically set to email-or-phone, added phone field
* django-phone-auth - separate email and phone models, unique, verified boolean, linked to a User. Uses signals verifying email/phone/resetting. Login with phone/email/username and password.
* django-phoneuser - user that has phone, not email or username. Has a OTP model to generate/verify a one-time code.
* django-allauth - has EmailAddress/EmailConfirmation/SocialAccount models. Handles many third parties, but very email/confirmation link based
* django-phone-verify - DRF reliant; sends code for verification.

Options (the Case always stores its own details, of course)
1. Stored like a spreadsheet. The case stores name/email/phone/address/"best time"/etc. User stores email and phone. You log in via email/phone verification to create Account for that email/phone only. Can access cases with matching email/phone. Pros: no need to try and link up cases with accounts. Cons: No linkage for e.g. easy email updating, central phone number associated with an email account.

2. Same as FixMyStreet. Case stores a user ID. User stores name, email, email_verified, phone, phone_verified, address, "best time" etc. If only email given, or both but phone landline, store on an email-verified Account. If only phone, store on Account for that phone. If both, store on Account whatever they said "best form of contact" was. Log in via email/phone verification to access that Account. Pros: known model. Cons: Bit more complex, doesn't match any of existing packages.

**Comment by dracos** [comment]
Going to stick with password-reset-style links in interests of security. But to aid different-browser use case (eg. wanting to leave noise report on computer but being sent log in token by phone), will try and show a code to user after clicking link that you can then enter on different device to 'convert' the login to that device. (can't do anything automatic due to baddies)
