### ISSUE TITLE
Perpetrator section of case page

### ISSUE THREAD

**Issue by dracos** [mysociety/noiseworks#41]
Could be more than one, I assume. m2m table?
![image](https://user-images.githubusercontent.com/154364/125778018-43442939-9fce-4104-b478-ddedaa961414.png)

**Comment by zarino** [comment]
@dracos I think we can close this now, right, as it was implemented by https://github.com/mysociety/noiseworks/pull/58?

**Comment by zarino** [comment]
Oh, or maybe it should be left open, but in the "Awaiting customer review" column of the SocietyWorks board?

**Comment by dracos** [comment]
This exists as a m2m table and you can add/remove, that's all at present.
