### ISSUE TITLE
Ability to add private notes to a case

### ISSUE THREAD

**Issue by LouiseMySociety** [mysociety/noiseworks#42]

**Comment by dracos** [comment]
Any action can have accompanying private notes. So two options - have an action that is "Add private note" if they want to be able to add a note without an accompanying action; or have a separate private notes field on a case, separate from actions, that they can edit. (Are private notes a note within a timeline of events, or a separate 'whiteboard' for the case)

**Comment by zarino** [comment]
We probed around this during the end-to-end testing. A few officers expected to be able to leave notes on a case, but when pushed, they couldn’t name an example of a note that wouldn’t _also_ be associated with one of the actions in the list (eg: leaving a note after contacting a complainant, or leaving a link to a notice that was sent out).

That said, a new action of "Add a private note" seems harmless enough, just in case they do eventually think of a real need for it.

**Comment by dracos** [comment]
Added action
