### ISSUE TITLE
Local development environment

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#6]
Docker? Or just a virtualenv?

**Comment by dracos** [comment]
I have created initial things as follows:
* Poetry is used for package management - poetry add to add a new package, we commit the lock file for installation, etc.
* Dockerfile - This builds the web container as multi-stage build, it installs poetry and runs poetry install; then installs geo stuff and copies across the built packages. Could perhaps do production in here as well potentially?
* docker-compose.yml - this has the web container from the Dockerfile, and a database container, and that's it.

**Comment by dracos** [comment]
@davea used this okay to set up, so I think this can be considered done initially at least.

**Comment by davea** [comment]
Just to note that on my M1-based Mac the official PostGIS docker image doesn't work (https://github.com/docker/for-mac/issues/5122, https://github.com/postgis/docker-postgis/issues/216) so I had to make the following change to `docker-compose.yml`:

```diff
 services:
   db:
-    image: postgis/postgis:13-3.1
+    # image: postgis/postgis:13-3.1
+    image: gangstead/postgis:13-3.1-arm
     restart: always
     volumes:
       - pgdata:/var/lib/postgresql/data
```

**Comment by dracos** [comment]
For local dev it really needs to leave poetry installed for development, this is more assuming production and setting up a slimmer build.
