### ISSUE TITLE
Homepage, header, and footer tidy up

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#62]
![Screenshot 2021-11-16 at 15-41-49 Hackney Council](https://user-images.githubusercontent.com/739624/142017106-1f14a4e0-f8c1-4346-a749-6a09a2bc087f.png)

* "My cases / Unassigned / All" links shouldn’t be visible to logged-out users
* Homepage should have some content on it – perhaps some form of [Start page](https://design-system.service.gov.uk/patterns/start-pages/), with a big button for citizens to view their past cases, and a smaller link for staff to sign in
* "Powered by" in footer isn’t using the same font as all the other text on the page

**Comment by dracos** [comment]
(Nav is now My/New for logged-out users.)
