### ISSUE TITLE
Concept of “followers” of a case? (Or multiple “assignees” with one “lead assignee”)

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#67]
Notes from a recent discussion with Hackney housing officers:

> Enforcement and Housing teams will often both be involved in a case. Sometimes a Housing or Enforcement officer might “lead” on a case, while their counterpart in the other team might be “following” it, backing up. May need to switch the “lead” as a case evolves.
>
> If Housing ASB is involved in a case, usually the Housing ASB officer will be the “lead” on the case, because they have all the relationships with the tenants.
>
> Usually it’d only be the Lead officer on a case that would communicate with the complainant(s).

We could describe this as either multiple assignees, with some form of extra metadata to show that one of the assignees at any one time is the "lead". Or we could keep "assignee" == "lead", and add another type of relationship like "following".

Either way, if you’re assigned to or following a case, it should appear in your "My cases" list.

There was a suggestion that we might only want to allow assigned / following officers to edit case details – but that feels like a discussion for a separate ticket, given right now anybody can edit anything.

**Comment by dracos** [comment]
We've implemented this as followers separate from assignee at the moment, with a separate filter to show them.
