### ISSUE TITLE
Consider how we’ll track changes to attributes and things within cases

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#7]
For example, when a case is (re-)assigned, we should be able to see that "update" in the case history – "Bob Smith (TSO) reassigned this case to Alice White (PEO) on YYYY-MM-DD HH:MM"

**Comment by dracos** [comment]
Going to try django-pghistory

**Comment by dracos** [comment]
Was more complex than hoped, and did not make things easier. Have Action table for logging manual actions, that is also currently used for reassignments and merges.
