### ISSUE TITLE
Citizen-facing UI improvements

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#75]
- [x] Homepage – show "Start" page, if not logged in staff member?
- [x] "Sign out" link(s) should take you to a "you’ve signed out" page
- [x] Should limit widths of short text inputs during citizen login/reporting flows (name, email, phone, token are all currently 100% width, looks odd)
- [x] Do we control the text of the login token/magic link email/SMS? My instinct was the token should go first, early on in the message, with the link as a secondary action, later on. Eg: "Your Hackney NoiseWorks login token is XXXXXXX. Alternatively, you can log on this device by following this link: https://yyyyyyy.hackney.gov.uk/a/zzzzzzzzzzzz"

And some more:
- [x] Normal user leaving reoccurrence gives error
- [x] New case, normal user address isn't shown on summary page
- [x] Add email/phone confirmation for new case form if not signed in
- [x] If signed in, have email/phone uneditable, with sign out text/link
- [x] Case logged page, normal user have My cases and "Finish and leave service"
- [x] New case summary, change your details link doesn't work

**Comment by dracos** [comment]
Moving text needed elsewhere, so this is all done
