### ISSUE TITLE
Missing title on non-logged-in report confirmation step

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#79]
I started a new report, in a private window, providing a (real) email and (fake) phone number, and this is what I saw after I’d entered all the report details and submitted:

<img width="1340" alt="Screenshot 2021-12-19 at 13 36 57" src="https://user-images.githubusercontent.com/739624/146676888-fce3bdb6-e4b9-4fe1-83a6-3d48a1fa197a.png">

This screen is missing instructions on what the token is and where to find it.

A token was emailed to me – although, worth noting it didn’t look like all the other HTML emails:

<img width="766" alt="Screenshot 2021-12-19 at 13 40 30" src="https://user-images.githubusercontent.com/739624/146676964-e71c31ad-e2a0-4de9-8400-8299cbc268c2.png">

(Sorry, maybe that email thing is a separate issue!)

**Comment by dracos** [comment]
Title/help added in db5d684, styling in 533f6f2
