### ISSUE TITLE
Citizen reporting form presents an error on submitting "your address" postcode

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#80]
Reporting as a non-logged-in user. Entered my name, email, phone, submitted. Entered my postcode, submitted. Saw this on the next pageload:

<img width="1340" alt="Screenshot 2021-12-19 at 13 42 44" src="https://user-images.githubusercontent.com/739624/146677038-8ca7ae41-c06d-42b0-8a94-3d5f821587d8.png">

The form on this shouldn’t be in an error state, as I haven’t had a chance to interact with it yet!

**Comment by dracos** [comment]
Yeah, I did this not great but the flow worked so I left it, knew someone would pick it up. Geocode did it a better way, so I've adapted that in b24f91b to behave the same here.
