### ISSUE TITLE
When logged in as a citizen, and reporting a new issue, contact preferences should be pre-filled

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#82]
Feels a bit weird that we pre-fill your name, email (uneditable), and phone number, but then on the next screen, we make you tell us your contact preferences afresh:

<img width="1407" alt="Screenshot 2021-12-19 at 15 23 14" src="https://user-images.githubusercontent.com/739624/146680567-152484cb-ab4c-4fa9-9216-40d56cb01eb7.png">

(…TBH I’m also wondering why we ask you for your address again too – are we worried that you will have moved house since your last report? Perhaps we could display what we think your address is, and let you optionally change it?)

**Comment by dracos** [comment]
16eb0e1ae2d75d19f33c21f42b628bafc5cbf56b should remember best time/method if logged in now. Address is harder - we only store UPRN or manual-address if given, so don't have a postcode to prefill (we'd either have to store it, look it up from UPRN or parse it out of manual...) - so your solution is the best I think, displaying it if logged in with a 'change' that would start from empty postcode box again. Bit bigger than rest of tickets.
