### ISSUE TITLE
"My cases" button after reporting an issue shouldn’t require me to request another login token

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#83]
I’ve just submitted a new report as a citizen. I had to confirm my report by providing a login token. But clicking the "My cases" button on the success page requires me to submit yet another token. Why do I have to do this twice in such quick succession? If I’ve just authenticated myself to submit the report, it seems weird to have to authenticate again just to see the details of that report.

**Comment by dracos** [comment]
0ed1c21 means it will now sign you in when you enter a login token. Might want some more prominent "Finish and leave" buttons if this means they're signed in, or some other more complex mechanism (e.g. perhaps they're not signed in *unless* they click My cases in which case they will be? Something like that...).
