### ISSUE TITLE
Sort out my cases / my wards / my followed / all cases confusion

### ISSUE THREAD

**Issue by zarino** [mysociety/noiseworks#85]
My cases, My wards, and My followed cases all feel like related concepts, but they’re handled differently.

"My cases" gets its own nav bar item, but doesn’t include "followed" cases by default. This surprised a few officers in user testing yesterday. And they didn’t expect to find "cases I’m following" as an option under the "Assigned" select box label.

"My wards" doesn’t have a navbar link, but in actuality "All cases" does currently operate as "My wards" because, when you have wards assigned to you, and you click "All cases" in the nav bar, you see a list of cases _in your wards only_. This feels like a bug. One or two officers were caught out by this in user testing yesterday.

**Comment by dracos** [comment]
Agreed, this has accreted to this
